<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.synditcorp</groupId>
  <artifactId>ruleengine</artifactId>
  <packaging>jar</packaging>
  <version>3.0.2-RELEASE</version>
  <name>${project.groupId}:${project.artifactId}</name>
  <description>A rule engine for business rule implementations.</description>
  <url>https://github.com/syndit/com.synditcorp.ruleengine/tree/3.0</url>
  <properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
  </properties>
  <licenses>
	  <license>
	    <name>MIT License</name>
	    <url>http://www.opensource.org/licenses/mit-license.php</url>
	  </license>
	</licenses>
	<developers>
    <developer>
      <name>Alan Jack</name>
      <email>alan.jack@synditcorp.com</email>
      <organization>Syndit Business Solutions, Inc.</organization>
    </developer>
  </developers>
  <scm>
    <connection>scm:git:git://github.com/syndit/com.synditcorp.ruleengine/tree/3.0</connection>
    <url>https://github.com/syndit/com.synditcorp.ruleengine/tree/3.0</url>
 	<developerConnection>scm:git:git://github.com/syndit/com.synditcorp.ruleengine/tree/3.0</developerConnection>
   </scm>

	<distributionManagement>
        <snapshotRepository>
            <id>central-snapshot</id>
            <url>https://central.sonatype.org/publish/publish-portal-snapshots/</url>
        </snapshotRepository>
        <repository>
            <id>central-release</id>
            <url>https://central.sonatype.org/publish/publish-portal-releases/</url>
        </repository>
    </distributionManagement>

  <build>
    <sourceDirectory>src/main/java</sourceDirectory>
    <plugins>
      <plugin>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>3.14.0</version>
        <configuration>
           <source>17</source>
          <target>17</target>
          <release>17</release>
        </configuration>
      </plugin>
	  <plugin>
	    <groupId>org.apache.maven.plugins</groupId>
	    <artifactId>maven-gpg-plugin</artifactId>
	    <version>3.2.8</version>
	    <executions>
	      <execution>
	        <id>sign-artifacts</id>
	        <phase>verify</phase>
	        <goals>
	          <goal>sign</goal>
	        </goals>
			<configuration>
				<keyname>${gpg.keyname}</keyname>
 				<passphraseServerId>${gpg.keyname}</passphraseServerId>
			</configuration>
 	      </execution>
	    </executions>
	  </plugin>
	  <plugin>
		<groupId>org.apache.maven.plugins</groupId>
		<artifactId>maven-deploy-plugin</artifactId>
		<version>3.1.4</version>
		<executions>
			<execution>
				<id>default-deploy</id>
				<phase>deploy</phase>
				<goals>
					<goal>jar</goal>
					<goal>deploy</goal>
				</goals>
			</execution>
		</executions>
	  </plugin>

      <plugin>
        <groupId>org.sonatype.central</groupId>
        <artifactId>central-publishing-maven-plugin</artifactId>
        <version>0.8.0</version>
        <extensions>true</extensions>
        <configuration>
          <publishingServerId>central-release</publishingServerId>
        </configuration>
      </plugin>

      
      
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-javadoc-plugin</artifactId>
        <version>3.11.2</version>
		<executions>
			<execution>
				<goals>
					<goal>jar</goal>
				</goals>
 			</execution>
		</executions>
	    <configuration>
    	    <doclint>none</doclint>
        </configuration>
      </plugin>
	  <plugin>
		<groupId>org.apache.maven.plugins</groupId>
		<artifactId>maven-source-plugin</artifactId>
    	<version>3.3.1</version>
		<executions>
			<execution>
				<id>attach-sources</id>
				<goals>
					<goal>jar</goal>
				</goals>
			</execution>
		</executions>
	   </plugin>
	   <plugin>
			<groupId>org.apache.maven.plugins</groupId>
			<artifactId>maven-surefire-plugin</artifactId>
			<version>3.5.3</version>
		</plugin>
 	</plugins>
  </build>
 <dependencies>
  	<dependency>
  		<groupId>com.fasterxml.jackson.core</groupId>
  		<artifactId>jackson-databind</artifactId>
  		<version>2.19.1</version>
  	</dependency>
  	<dependency>
  		<groupId>org.mvel</groupId>
  		<artifactId>mvel2</artifactId>
  		<version>2.5.2.Final</version>
  	</dependency>

   	<dependency>
		<groupId>org.apache.logging.log4j</groupId>
  		<artifactId>log4j-core</artifactId>
    	<version>2.25.1</version>
	</dependency>
  	
	<dependency>
    	<groupId>org.junit.jupiter</groupId>
    	<artifactId>junit-jupiter-engine</artifactId>
    	<version>5.13.3</version>
    	<scope>test</scope>
	</dependency>
</dependencies>
</project>